### ISSUE TITLE
Don't display driver tab content if no car

### ISSUE THREAD

**Issue by NickolasHansen** [rideshare1707/rideshare#17]

**Comment by NickolasHansen** [comment]
first commit soon

**Comment by duncanandyw** [comment]
Current: User can still see all driver functionality and attempt to create an offer/accept a request even if they don't have a car.

Expected: If a user does not have a car display a message w/ link to profile instead of driver functionality.

**Comment by DirkEnthoven** [comment]
need to compare the response to a string  '' means that the user has no car
